onboarding = false

[ui.toast]
delivery = "herdr"

[theme]
name = "terminal"
auto_switch = false

[keys]

prefix = "ctrl+b"

detach = "prefix+q"

# Close
close_pane = "prefix+x"
close_tab = "prefix+w"
close_workspace = "prefix+shift+w"

# Splits
split_vertical = "prefix+d"
split_horizontal = "prefix+shift+d"

# Navigation 
focus_pane_left = "prefix+h"
focus_pane_down = "prefix+j"
focus_pane_up = "prefix+k"
focus_pane_right = "prefix+l"

# Workspaces
switch_workspace = "prefix+1..9"
workspace_picker = "prefix+shift+s"
new_workspace = "prefix+shift+t"
previous_workspace = "prefix+shift+o"
next_workspace = "prefix+shift+p"
rename_workspace = "prefix+shift+r"

# Move panes
swap_pane_left = "prefix+shift+h"
swap_pane_down = "prefix+shift+j"
swap_pane_up = "prefix+shift+k"
swap_pane_right = "prefix+shift+l"

# Tabs 
next_tab = "prefix+p"
previous_tab = "prefix+o"
rename_tab = "prefix+r"
new_tab = "prefix+t"

# Resize
resize_mode = "prefix+c"

# Reload Config
reload_config = "prefix+shift+c"
